### ISSUE TITLE
Did something change recently? My extension is now getting a 404 response.

### ISSUE THREAD

**Issue by MatthewFoulk** [planetterp/PlanetTerp-API#6]
I noticed tonight that I no longer was seeing PlanetTerp's results for my professor rating plugin. I checked a few other similar plugins to see if it was just mine experiencing the error, and it appeared the others were also having difficulties. Any idea if anything has changed recently that could be causing this? This is what I see in the console.

<img width="759" alt="image" src="https://user-images.githubusercontent.com/17619262/185284936-969650d8-9d3d-40d6-81d1-50798ed57edd.png">

**Comment by tybug** [comment]
good to know I'm not the only one maintaining such a plugin (I maintain a similar plugin [here](https://github.com/tybug/testudoplus)). We updated the base api url to be https://planetterp.com/api/v1 instead of https://api.planetterp.com/v1 - we'd hoped to include a redirect as well when we made the change, but were a bit slow on the draw. For an immediate fix, you can update your api calls to the new url. 

You might also be interested to know that planetterp is now open source https://github.com/planetterp/planetterp - we'll announce it on the subreddit soon, but consider this a sneak peak :)

**Comment by tybug** [comment]
api redirection is fixed now and your script should work without any modification. The old base url (https://api.planetterp.com/) is deprecated and may be turned off in the future though, so you should update your script at some point if you haven't already.
